name: downloadmanager
description: A new Flutter project. 
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.11.4 
  provider: ^6.1.0
  http: ^1.1.0
  uuid: ^4.2.1
  path_provider: ^2.0.11
  android_path_provider: ^0.3.0
  permission_handler: ^10.0.0
  device_info_plus: ^8.0.0
  sqflite:
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0 
flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/

